### ISSUE TITLE
Note numpy must be installed first

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/pymartini#10]
Because I don't currently distribute wheels, pymartini must be compiled from sources when it's downloaded. To do that, it needs to find the numpy headers
https://github.com/kylebarron/pymartini/blob/5b43553e4837437a5734edb78eec501085cb767f/setup.py#L49-L50

But numpy won't necessarily have been installed yet, so maybe add a note to the README explaining that numpy must exist _before_ installing.

You could probably try installing into a new virtualenv to see what happens.

**Comment by kylebarron** [comment]
In a new conda env, you do get an error saying numpy not available:
```
> pip install pymartini
Collecting pymartini
  Downloading pymartini-0.2.0.tar.gz (270 kB)
     |████████████████████████████████| 270 kB 2.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/kyle/local/anaconda3/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6v/4_10tk8549bc7yrbycgd2c540000gn/T/pip-install-mzi2g3wb/pymartini/setup.py'"'"'; __file__='"'"'/private/var/folders/6v/4_10tk8549bc7yrbycgd2c540000gn/T/pip-install-mzi2g3wb/pymartini/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6v/4_10tk8549bc7yrbycgd2c540000gn/T/pip-install-mzi2g3wb/pymartini/pip-egg-info
         cwd: /private/var/folders/6v/4_10tk8549bc7yrbycgd2c540000gn/T/pip-install-mzi2g3wb/pymartini/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6v/4_10tk8549bc7yrbycgd2c540000gn/T/pip-install-mzi2g3wb/pymartini/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
